source 'https://rubygems.org'
# You may use https://github.com/rbenv/rbenv or https://rvm.io/ to install and use this version
ruby File.read(File.join(__dir__, '.ruby-version')).strip
gem 'cocoapods', '~> 1.11', '>= 1.11.3'
